server {
    listen       1409;
    server_name  localhost;
    charset utf-8;

    root   /var/www/reshu/zhuzhouMes/zz_mes_web/dist;
    index  index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page  404              /404.html;
    error_page  500 502 503 504  /50x.html;
    location = /50x.html {
        root   /var/www/reshu/zhuzhouMes/zz_mes_web/dist;
    }

    # 禁止访问隐藏文件
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
